### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by NNTin** [judge0/discord-bot#4]
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose. - [choosealicense.com](https://choosealicense.com/no-permission/)

Please add a license. Currently potential contributors do not have the permission to develop on their own discord bot instance. They have a right to fork the project as per GitHub ToS but they do not have permission to modify it and running their own local instance.

**Comment by skilldeliver** [comment]
Thanks for the suggestion.

Now the Judge0 bot is under MIT license.
https://github.com/judge0/discord-bot/blob/master/LICENSE
